


rollback;

--게시글 목록 조회
-- BOARD 테이블 : BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, READ_COUNT,MEMBER_NO

SELECT BOARD_NO, BOARD_TITLE, CREATE_DATE, READ_COUNT, MEMBER_NM
FROM BOARD
JOIN MEMBER USING (MEMBER_NO)
ORDER BY BOARD_NO DESC;


--게시글 삭제
DELETE FROM BOARD
WHERE BOARD_NO = ?;

ALTER TABLE REPLY DROP CONSTRAINT SYS_C007590;

ALTER TABLE REPLY ADD FOREIGN_KEY REFERENCES BOARD (BOARD_NO) ON DELETE CASCADE;



