prompt 워크북용 스크립트

set feedback off
set define off

DROP TABLE TB_DEPARTMENT CASCADE CONSTRAINTS;
PROMPT DROPPING TB_CLASS...
DROP TABLE TB_CLASS CASCADE CONSTRAINTS;
PROMPT DROPPING TB_PROFESSOR...
DROP TABLE TB_PROFESSOR CASCADE CONSTRAINTS;
PROMPT DROPPING TB_CLASS_PROFESSOR...
DROP TABLE TB_CLASS_PROFESSOR CASCADE CONSTRAINTS;
PROMPT DROPPING TB_STUDENT...
DROP TABLE TB_STUDENT CASCADE CONSTRAINTS;
PROMPT DROPPING TB_GRADE...
DROP TABLE TB_GRADE CASCADE CONSTRAINTS;



PROMPT CREATING TB_DEPARTMENT...
CREATE TABLE TB_DEPARTMENT
(
  DEPARTMENT_NO   VARCHAR2(10) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(40) NOT NULL,
  CATEGORY        VARCHAR2(40),
  OPEN_YN         CHAR(1),
  CAPACITY        NUMBER
)
;
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO  IS '학과 번호';
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NAME  IS '학과 이름';
COMMENT ON COLUMN TB_DEPARTMENT.CATEGORY  IS '계열';
COMMENT ON COLUMN TB_DEPARTMENT.OPEN_YN  IS '개설 여부';
COMMENT ON COLUMN TB_DEPARTMENT.CAPACITY  IS '정원';

ALTER TABLE TB_DEPARTMENT
  ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_NO);


PROMPT CREATING TB_CLASS...
CREATE TABLE TB_CLASS
(
  CLASS_NO              VARCHAR2(10) NOT NULL,
  DEPARTMENT_NO         VARCHAR2(20) NOT NULL,
  PREATTENDING_CLASS_NO VARCHAR2(20),
  CLASS_NAME            VARCHAR2(60) NOT NULL,
  CLASS_TYPE            VARCHAR2(20)
)
;
COMMENT ON COLUMN TB_CLASS.CLASS_NO  IS '과목 번호';
COMMENT ON COLUMN TB_CLASS.DEPARTMENT_NO  IS '학과 번호';
COMMENT ON COLUMN TB_CLASS.PREATTENDING_CLASS_NO  IS '선수 과목 번호';
COMMENT ON COLUMN TB_CLASS.CLASS_NAME  IS '과목 이름';
COMMENT ON COLUMN TB_CLASS.CLASS_TYPE  IS '과목 구분';

ALTER TABLE TB_CLASS  ADD CONSTRAINT PK_CLASS PRIMARY KEY (CLASS_NO);
ALTER TABLE TB_CLASS  ADD CONSTRAINT FK_CLASS_01 FOREIGN KEY (PREATTENDING_CLASS_NO)
  REFERENCES TB_CLASS (CLASS_NO) ON DELETE SET NULL;
ALTER TABLE TB_CLASS  ADD CONSTRAINT FK_CLASS_02 FOREIGN KEY (DEPARTMENT_NO)
  REFERENCES TB_DEPARTMENT (DEPARTMENT_NO);

PROMPT CREATING TB_PROFESSOR...
CREATE TABLE TB_PROFESSOR
(
  PROFESSOR_NO      VARCHAR2(10) NOT NULL,
  PROFESSOR_NAME    VARCHAR2(40) NOT NULL,
  PROFESSOR_SSN     VARCHAR2(14),
  PROFESSOR_ADDRESS VARCHAR2(200),
  DEPARTMENT_NO     VARCHAR2(20)
)
;
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NO  IS '교수 번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NAME  IS '교수 이름';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_SSN  IS '교수 주민번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_ADDRESS  IS '교수 주소';

ALTER TABLE TB_PROFESSOR
  ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (PROFESSOR_NO);
ALTER TABLE TB_PROFESSOR
  ADD CONSTRAINT FK_PROFESSOR_DEPARTMENTNO FOREIGN KEY (DEPARTMENT_NO)
  REFERENCES TB_DEPARTMENT (DEPARTMENT_NO);

PROMPT CREATING TB_CLASS_PROFESSOR...
CREATE TABLE TB_CLASS_PROFESSOR
(
  CLASS_NO     VARCHAR2(10) NOT NULL,
  PROFESSOR_NO VARCHAR2(10) NOT NULL
)
;
COMMENT ON COLUMN TB_CLASS_PROFESSOR.CLASS_NO  IS '과목 번호';
COMMENT ON COLUMN TB_CLASS_PROFESSOR.PROFESSOR_NO  IS '교수 번호';

ALTER TABLE TB_CLASS_PROFESSOR
  ADD CONSTRAINT PK_CLASS_PROFESSOR PRIMARY KEY (CLASS_NO, PROFESSOR_NO);
ALTER TABLE TB_CLASS_PROFESSOR
  ADD CONSTRAINT FK_CLASS_PROFESSOR_01 FOREIGN KEY (PROFESSOR_NO)
  REFERENCES TB_PROFESSOR (PROFESSOR_NO);
ALTER TABLE TB_CLASS_PROFESSOR
  ADD CONSTRAINT FK_CLASS_PROFESSOR_02 FOREIGN KEY (CLASS_NO)
  REFERENCES TB_CLASS (CLASS_NO);

PROMPT CREATING TB_STUDENT...
CREATE TABLE TB_STUDENT
(
  STUDENT_NO         VARCHAR2(10) NOT NULL,
  DEPARTMENT_NO      VARCHAR2(10) NOT NULL,
  STUDENT_NAME       VARCHAR2(40) NOT NULL,
  STUDENT_SSN        VARCHAR2(14),
  STUDENT_ADDRESS    VARCHAR2(200),
  ENTRANCE_DATE      DATE,
  ABSENCE_YN         CHAR(1),
  COACH_PROFESSOR_NO VARCHAR2(20)
)
;
COMMENT ON COLUMN TB_STUDENT.STUDENT_NO  IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.DEPARTMENT_NO  IS '학과 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME  IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN  IS '학생 주민번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_ADDRESS  IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE  IS '입학 년도';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN  IS '휴학 여부';
COMMENT ON COLUMN TB_STUDENT.COACH_PROFESSOR_NO  IS '지도 교수 번호';

ALTER TABLE TB_STUDENT
  ADD CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENT_NO);
ALTER TABLE TB_STUDENT
  ADD CONSTRAINT FK_STUDENT_01 FOREIGN KEY (DEPARTMENT_NO)
  REFERENCES TB_DEPARTMENT (DEPARTMENT_NO);
ALTER TABLE TB_STUDENT
  ADD CONSTRAINT FK_STUDENT_02 FOREIGN KEY (COACH_PROFESSOR_NO)
  REFERENCES TB_PROFESSOR (PROFESSOR_NO) ON DELETE SET NULL;

PROMPT CREATING TB_GRADE...
CREATE TABLE TB_GRADE
(
  TERM_NO    VARCHAR2(10) NOT NULL,
  STUDENT_NO VARCHAR2(10) NOT NULL,
  CLASS_NO   VARCHAR2(10) NOT NULL,
  POINT      NUMBER(3,2)
)
;
COMMENT ON COLUMN TB_GRADE.TERM_NO  IS '학기 번호';
COMMENT ON COLUMN TB_GRADE.STUDENT_NO  IS '학생 번호';
COMMENT ON COLUMN TB_GRADE.CLASS_NO  IS '과목 번호';
COMMENT ON COLUMN TB_GRADE.POINT  IS '학점';

ALTER TABLE TB_GRADE
  ADD CONSTRAINT PK_GRADE PRIMARY KEY (TERM_NO, CLASS_NO, STUDENT_NO);
ALTER TABLE TB_GRADE
  ADD CONSTRAINT FK_GRADE_01 FOREIGN KEY (STUDENT_NO)
  REFERENCES TB_STUDENT (STUDENT_NO);
ALTER TABLE TB_GRADE
  ADD CONSTRAINT FK_GRADE_02 FOREIGN KEY (CLASS_NO)
  REFERENCES TB_CLASS (CLASS_NO);

--PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_DEPARTMENT...
--ALTER TABLE TB_DEPARTMENT DISABLE CONSTRAINT FK_DEPARTMENT_01;
PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_CLASS...
ALTER TABLE TB_CLASS DISABLE CONSTRAINT FK_CLASS_01;
ALTER TABLE TB_CLASS DISABLE CONSTRAINT FK_CLASS_02;
PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_PROFESSOR...
ALTER TABLE TB_PROFESSOR DISABLE CONSTRAINT FK_PROFESSOR_DEPARTMENTNO;
PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_CLASS_PROFESSOR...
ALTER TABLE TB_CLASS_PROFESSOR DISABLE CONSTRAINT FK_CLASS_PROFESSOR_01;
ALTER TABLE TB_CLASS_PROFESSOR DISABLE CONSTRAINT FK_CLASS_PROFESSOR_02;
PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_STUDENT...
ALTER TABLE TB_STUDENT DISABLE CONSTRAINT FK_STUDENT_01;
ALTER TABLE TB_STUDENT DISABLE CONSTRAINT FK_STUDENT_02;
PROMPT DISABLING FOREIGN KEY CONSTRAINTS FOR TB_GRADE...
ALTER TABLE TB_GRADE DISABLE CONSTRAINT FK_GRADE_01;
ALTER TABLE TB_GRADE DISABLE CONSTRAINT FK_GRADE_02;



PROMPT LOADING TB_DEPARTMENT...
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('001', '국어국문학과', '인문사회', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('002', '영어영문학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('003', '사학과', '인문사회', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('004', '철학과', '인문사회', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('005', '법학과', '인문사회', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('006', '행정학과', '인문사회', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('007', '정치학과', '인문사회', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('008', '경제학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('009', '사회학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('010', '무역학과', '인문사회', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('011', '신문방송학과', '인문사회', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('012', '경영학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('013', '회계학과', '인문사회', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('014', '호텔관광학과', '인문사회', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('015', '교육학과', '인문사회', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('016', '영미어문화학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('017', '불어불문학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('018', '중어중문학과', '인문사회', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('019', '일어일문학과', '인문사회', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('020', '서반아어학과', '인문사회', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('021', '국제경영학과', '인문사회', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('022', '수학과', '자연과학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('023', '물리학과', '자연과학', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('024', '화학과', '자연과학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('025', '생물학과', '자연과학', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('026', '지리학과', '자연과학', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('027', '아동주거학과', '자연과학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('028', '의상학과', '자연과학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('029', '식품영양학과', '자연과학', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('030', '약학과', '자연과학', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('031', '임상약학과', '자연과학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('032', '한약학과', '자연과학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('033', '간호학과', '자연과학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('034', '환경조경학과', '자연과학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('035', '생명공학원', '자연과학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('036', '우주과학과', '자연과학', 'Y', 24);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('037', '한방재료가공학과', '자연과학', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('038', '생태시스템공학과', '자연과학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('039', '식품생명공학과', '자연과학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('040', '원예학과', '자연과학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('041', '환경응용과학과', '자연과학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('042', '원자력공학과', '공학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('043', '전자공학과', '공학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('044', '컴퓨터공학과', '공학', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('045', '건축공학과', '공학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('046', '토목공학과', '공학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('047', '기계공학과', '공학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('048', '전파공학과', '공학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('049', '산업공학과', '공학', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('050', '섬유공학과', '공학', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('051', '화학공학과', '공학', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('052', '동서의료공학과', '공학', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('053', '의학과', '의학', 'Y', 40);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('054', '한의학과', '의학', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('055', '치의학과', '의학', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('056', '미술학과', '예체능', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('057', '무용학과', '예체능', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('058', '공연예술학과', '예체능', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('059', '음악학과', '예체능', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('060', '도예학과', '예체능', 'Y', 36);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('061', '산업디자인학과', '예체능', 'Y', 28);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('062', '디자인학과', '예체능', 'Y', 32);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('063', '체육학과', '예체능', 'Y', 24);
COMMIT;
PROMPT 63 RECORDS LOADED
PROMPT LOADING TB_CLASS...
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0245500', '001', NULL, '고전시가론특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0405000', '001', NULL, '국어어휘론특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0405500', '001', 'C0405000', '국어음성학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0409000', '001', 'C0405000', '국어학세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1914600', '001', NULL, '시화야담특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1987000', '001', NULL, '신화연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4890800', '001', NULL, '영상문화이론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5011100', '001', NULL, '외국어로서의한국어습득연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3802900', '001', NULL, '판소리특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4913400', '001', NULL, '한국어교육론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3936400', '001', NULL, '한국어어휘교육론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3953700', '001', NULL, '한국현대문학사연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4034800', '001', NULL, '현대문학특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4047300', '001', NULL, '현대소설연구1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4048400', '001', NULL, '현대시문학특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4059400', '001', NULL, '현대작가론특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736733', '001', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737033', '001', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737533', '001', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0003400', '002', NULL, '19C미국소설', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1105000', '002', NULL, '문학과생태학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1113900', '002', NULL, '문화이론과비평', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1811200', '002', NULL, '셰익스피어세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2364800', '002', NULL, '영어교육연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2554500', '002', NULL, '응용언어학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3745100', '002', NULL, '통사론1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3745400', '002', 'C3745100', '통사론세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736734', '002', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737034', '002', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737534', '002', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3167100', '003', NULL, '중국제도사연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3915900', '003', NULL, '한국대외관계사연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3927900', '003', NULL, '한국사특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736735', '003', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737035', '003', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737535', '003', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1350600', '004', NULL, '변증법연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1423100', '004', NULL, '불교철학의제문제', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1632600', '004', NULL, '사회철학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3834600', '004', NULL, '프랑스철학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736736', '004', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737036', '004', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737536', '004', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0165500', '005', NULL, '경제법특수연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5018500', '005', NULL, '계약론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010200', '005', NULL, '공범론연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010100', '005', NULL, '국제경제법특수연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0432500', '005', 'C0434900', '국제법연습', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0434900', '005', NULL, '국제사법일반이론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010000', '005', NULL, '국제전자상거래법 사례연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010300', '005', NULL, '규제행정법연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010600', '005', NULL, '민사소송절차의 기본원리', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1343200', '005', NULL, '법사회학특수연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010400', '005', NULL, '선거제도연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1803600', '005', NULL, '세법일반이론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010500', '005', NULL, '친족법특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5009900', '005', NULL, '통치기구론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5010700', '005', NULL, '특별형법연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736737', '005', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737037', '005', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737537', '005', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3052000', '006', NULL, '정책이론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0184100', '006', NULL, '계량분석론Ⅰ', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1317000', '006', NULL, '발전행정론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1618700', '006', NULL, '사회보장제도론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3048900', '006', NULL, '정책결정론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3051900', '006', 'C3048900', '정책사례연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3221500', '006', 'C3952800', '지방행정론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3952800', '006', NULL, '한국행정론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4014200', '006', NULL, '행정조직론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736738', '006', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737038', '006', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737538', '006', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0441200', '007', NULL, '국제정치경제', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0869000', '007', NULL, '동아시아국제관계', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1444500', '007', NULL, '비교외교정책론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1447200', '007', NULL, '비교정치학방법론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2589300', '007', NULL, '의회및선거론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4842400', '007', NULL, '정치와문화', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3059400', '007', NULL, '정치윤리학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3946100', '007', NULL, '한국정치론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736739', '007', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737039', '007', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737539', '007', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0164400', '008', NULL, '경제발전론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0473000', '008', NULL, '금융공학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0724200', '008', NULL, '노사관계론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736740', '008', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737040', '008', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737540', '008', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1625800', '009', NULL, '사회심리학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1637700', '009', NULL, '사회학이론연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C8033800', '009', NULL, '정치사회학(학점교류)', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3127700', '009', NULL, '종교사회학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736741', '009', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737041', '009', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737541', '009', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3101701', '010', NULL, '조사방법론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4561800', '010', NULL, '경영혁신과 글로벌E-비지니스', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4711500', '010', NULL, '국제경영전략', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0427000', '010', NULL, '국제마케팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0193000', '010', NULL, '고급거시경제학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2424700', '010', NULL, '외환론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0439300', '010', NULL, '국제재무관리', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0800400', '010', NULL, '다국적기업론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736742', '010', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737042', '010', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737542', '010', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0044900', '011', NULL, 'PR실무', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0321700', '011', NULL, '광고PR심리학', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0326400', '011', NULL, '광고표현론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0752300', '011', NULL, '뉴미디어론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1109400', '011', NULL, '문화간커뮤니케이션', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4428200', '011', NULL, '미디어와사회', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1847300', '011', NULL, '수사학개론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2346800', '011', NULL, '영상비평', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3061000', '011', NULL, '정치커뮤니케이션', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5014000', '011', NULL, '커뮤니케이션양적연구방법론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3606200', '011', NULL, '커뮤니케이션윤리법제론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5013900', '011', NULL, '커뮤니케이션질적연구방법론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5013800', '011', NULL, '커뮤니케이션효과이론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5014100', '011', NULL, '커뮤니케이션의기초', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736743', '011', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737043', '011', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737543', '011', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0144200', '012', NULL, '경영과학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0163001', '012', NULL, '경쟁분석론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0469800', '012', NULL, '글로벌경영세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0469801', '012', NULL, '글로벌경영세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0724201', '012', NULL, '노사관계론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0827900', '012', NULL, '데이터마이닝이론과실제', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1037000', '012', NULL, '마케팅정보공학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1357000', '012', NULL, '병원재무관리', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1433900', '012', NULL, '브랜드마케팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1815900', '012', NULL, '소비자행동론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4561600', '012', NULL, '연금계리 및 재무', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5009800', '012', NULL, '유비쿼터스컴퓨팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4349900', '012', NULL, '의료보험론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2621400', '012', NULL, '인적자원관리론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2626700', '012', NULL, '인터넷과전자상거래', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5021000', '012', NULL, '의료경영연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2941800', '012', NULL, '재무관리', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4847200', '012', NULL, '전략적인적자원개발', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3101700', '012', NULL, '조사방법론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3114700', '012', NULL, '조직행동론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5009700', '012', NULL, '지식경영연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3827100', '012', NULL, '품질경영', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736744', '012', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737044', '012', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737544', '012', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0217000', '013', NULL, '고급통계학1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1812500', '013', NULL, '소득세회계이론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2906500', '013', NULL, '자본시장회계연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4162000', '013', NULL, '회계학연구방법론1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736745', '013', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737045', '013', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737545', '013', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0291300', '014', NULL, '관광개발계획론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4562100', '014', NULL, '관광리조트개발론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4321400', '014', NULL, '관광응용경제학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0302800', '014', NULL, '관광자원세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4205700', '014', NULL, '레스토랑프렌차이즈', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4839200', '014', NULL, '무역전시기획론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1932800', '014', NULL, '식음료관리특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4562400', '014', NULL, '식품위생관리', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1953400', '014', NULL, '식품재료학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4851000', '014', NULL, '외식서비스마케팅세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4562500', '014', NULL, '컨벤션마케팅전략론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4427000', '014', NULL, '컨벤션실무통역', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3738800', '014', NULL, '통계분석', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4562200', '014', NULL, '한국관광정책세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4341700', '014', NULL, '호텔경영사례연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4426400', '014', NULL, '호텔관광정보론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4779000', '014', NULL, '호텔인사조직관리연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4507100', '014', NULL, '환대산업세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736746', '014', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737046', '014', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737546', '014', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2307001', '015', NULL, '연구방법론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5018400', '015', NULL, '교수학습공학이론및실천2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2604100', '015', NULL, '인간관계론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5009100', '015', NULL, '평생교육철학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736747', '015', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737047', '015', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737547', '015', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C7592000', '016', NULL, '언어와 성', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2573400', '016', NULL, '의미론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4037000', '016', NULL, '현대미국드라마연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736730', '016', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737001', '016', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737501', '016', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1428600', '017', NULL, '불소설연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1431900', '017', NULL, '불어통사론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2008300', '017', NULL, '실존주의불문학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736729', '017', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737002', '017', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737502', '017', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1339800', '018', NULL, '번역연습', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3143500', '018', NULL, '중국고대소설연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3171300', '018', NULL, '중국현대소설연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736704', '018', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737004', '018', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737505', '018', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2650400', '019', NULL, '일본극문학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4329800', '019', NULL, '일본어학세미나IV', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2675400', '019', NULL, '일본학세미나3', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736703', '019', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737003', '019', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737504', '019', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1728400', '020', NULL, '서반아고전문학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1753400', '020', NULL, '서어문체론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1753800', '020', NULL, '서어방언학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736706', '020', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737005', '020', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737506', '020', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5004600', '021', NULL, '고급소비자행동과 리서치', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5004800', '021', NULL, '고급인사조직세미나2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5004900', '021', NULL, '마케팅 데이터 모델 분석', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1159400', '021', NULL, '미시경제학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5004500', '021', NULL, '신기술 세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C7593200', '021', NULL, '인사조직행동 특별연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2625600', '021', NULL, '인터넷마케팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5004400', '021', NULL, '지식경영과 비지니스 인텔리전스', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736724', '021', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737024', '021', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737524', '021', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1141800', '022', NULL, '미분기하학특강1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1434900', '022', NULL, '비가환대수2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2475800', '022', NULL, '위상수학특강1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2925400', '022', NULL, '작용소론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736748', '022', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737048', '022', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737548', '022', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0247800', '023', NULL, '고전전자기학2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0250200', '023', NULL, '고체물리특론1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0250700', '023', NULL, '고체물리특수연구2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0251600', '023', NULL, '고체물리학2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2272800', '023', NULL, '양자역학II', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2547800', '023', NULL, '응용물리특론2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2714600', '023', NULL, '입자물리특론2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3740500', '023', NULL, '통계역학2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0247500', '023', NULL, '고전전자기학1', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2303500', '023', NULL, '역학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2468800', '023', NULL, '원자핵물리학1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2548000', '023', NULL, '응용물리특수연구2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4036800', '023', NULL, '현대물리학특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736790', '023', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737080', '023', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737580', '023', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0205100', '024', NULL, '고급양자화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1070500', '024', NULL, '무기화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1128501', '024', NULL, '물리화학세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2581600', '024', NULL, '의약화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4114500', '024', NULL, '화학기기장치법', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0197400', '024', NULL, '고급물리화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1128500', '024', NULL, '물리화학세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2485200', '024', NULL, '유기금속화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2491900', '024', NULL, '유기합성', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2548900', '024', NULL, '응용분석화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736751', '024', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737051', '024', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737551', '024', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1146100', '025', NULL, '미생물유전학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1412800', '025', NULL, '분자발생생물학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5007600', '025', NULL, '생태정보학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1795900', '025', NULL, '세균생리학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3095200', '025', NULL, '조류생리학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3096000', '025', NULL, '조류학(鳥類學)', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4880600', '025', NULL, '행동신경생물학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4880400', '025', NULL, '현대생물학연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4107500', '025', NULL, '화분학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736752', '025', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737052', '025', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737552', '025', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0171500', '026', NULL, '경제지리학특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0538400', '026', NULL, '기후지형학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0838900', '026', NULL, '도시지리학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0905200', '026', NULL, '디지털지도학연습', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1697000', '026', NULL, '생물지리학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4501400', '026', NULL, '수문지형학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3215100', '026', NULL, '지리정보학원론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736753', '026', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737053', '026', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737553', '026', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0070600', '027', NULL, '가족정책연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0138400', '027', NULL, '결혼및부부교육특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0838600', '027', NULL, '도시주택연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1997300', '027', NULL, '실내디자인사연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2208800', '027', NULL, '아동행동연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2307000', '027', NULL, '연구방법론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2502000', '027', NULL, '유아교육과정연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3422800', '027', NULL, '청년기발달', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736754', '027', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737054', '027', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737554', '027', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5007900', '028', NULL, '글로벌패션마케팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1024500', '028', NULL, '리테일패션마케팅', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1775400', '028', NULL, '섬유직물학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2576200', '028', NULL, '의복행동세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3803900', '028', NULL, '패션과대중문화', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3804400', '028', NULL, '패션디자인연구', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5008000', '028', NULL, '패션정보디자인', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736755', '028', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737055', '028', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737555', '028', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1070000', '029', NULL, '무기질대사', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1319200', '029', NULL, '발효식품', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1955401', '029', NULL, '식품학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2354400', '029', NULL, '영양역학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3742700', '029', NULL, '통계학2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736756', '029', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737056', '029', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737556', '029', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1694500', '030', NULL, '생물약제학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2011900', '030', NULL, '실험생화학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4893900', '030', NULL, '약학세미나2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2489700', '030', NULL, '유기약품합성반응특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2930800', '030', NULL, '장내세균학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C3108400', '030', NULL, '조제학특론및세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736757', '030', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737057', '030', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737557', '030', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0810500', '031', NULL, '당뇨병치료의최근동향', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5008300', '031', NULL, '약물독성경감제 개발', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C2580400', '031', NULL, '의약품기본론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736758', '031', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737058', '031', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737558', '031', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4501900', '032', NULL, '기기분석학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1381400', '032', NULL, '본초기원론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4568400', '032', NULL, '약용식물분류학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4502000', '032', NULL, '인체생리학특론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0736759', '032', NULL, '논문지도(공개발표)3', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737059', '032', NULL, '논문지도1', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0737559', '032', NULL, '논문지도2', '논문지도');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0085200', '033', NULL, '간호이론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0089400', '033', NULL, '간호현상과질적연구', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1666600', '033', NULL, '상급간호연구방법론', '전공필수');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5008100', '033', NULL, '가족상담과 정신간호', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0069400', '033', NULL, '가족상담실습', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0086100', '033', NULL, '간호정보학', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0106000', '033', NULL, '건강행위론', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C4866400', '033', NULL, '고급통계분석 및 세미나', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5014200', '033', NULL, '노인질환관리1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5015700', '033', NULL, '노인질환관리2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5015800', '033', NULL, '노인질환관리실습1', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C5015900', '033', NULL, '노인질환관리실습2', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C1359800', '033', NULL, '병태생리학', '전공선택');
INSERT INTO TB